local palette = require("badblood.palette")

local function get_groups()
	return {
		-- Base groups
		Normal = { fg = palette.fg, bg = palette.bg },
		NormalFloat = { fg = palette.fg, bg = palette.color0 }, -- Floating windows
		Comment = { fg = palette.color8, italic = true },
		Constant = { fg = palette.color4 },
		String = { fg = palette.color6 },
		Character = { fg = palette.color6 },
		Number = { fg = palette.color3 },
		Boolean = { fg = palette.color3 },
		Float = { fg = palette.color3 },
		Identifier = { fg = palette.color5 },
		Function = { fg = palette.color12 },
		Statement = { fg = palette.color4 },
		Conditional = { fg = palette.color4 },
		Repeat = { fg = palette.color4 },
		Label = { fg = palette.color4 },
		Operator = { fg = palette.fg },
		Keyword = { fg = palette.color4 },
		Exception = { fg = palette.color4 },
		PreProc = { fg = palette.color3 },
		Include = { fg = palette.color4 },
		Define = { fg = palette.color4 },
		Macro = { fg = palette.color4 },
		Type = { fg = palette.color7 },
		StorageClass = { fg = palette.color7 },
		Structure = { fg = palette.color7 },
		Typedef = { fg = palette.color7 },
		Special = { fg = palette.color13 },
		SpecialChar = { fg = palette.color5 },
		Tag = { fg = palette.color2 },
		Delimiter = { fg = palette.fg },
		Debug = { fg = palette.color1 },
		Underlined = { underline = true },
		Error = { fg = palette.color1, bold = true },
		Todo = { fg = palette.color3, bold = true },

		-- UI groups
		Cursor = { fg = palette.cursor_text, bg = palette.cursor },
		CursorLine = { bg = palette.color0 },
		CursorColumn = { bg = palette.color1 },
		LineNr = { fg = palette.color8 },
		CursorLineNr = { fg = palette.fg, bold = true },
		SignColumn = { bg = palette.bg },
		StatusLine = { fg = palette.fg, bg = palette.color0 },
		StatusLineNC = { fg = palette.color8, bg = palette.color0 },
		VertSplit = { fg = palette.color0 },
		ColorColumn = { bg = palette.color1 },
		Directory = { fg = palette.color4 },
		Visual = { fg = palette.selection_fg, bg = palette.selection_bg },
		VisualNOS = { bg = palette.selection_bg },
		WarningMsg = { fg = palette.color10 },
		WildMenu = { fg = palette.fg, bg = palette.selection_bg },
		Folded = { fg = palette.color8, bg = palette.color0 },
		FoldColumn = { fg = palette.color8 },
		DiffAdd = { fg = palette.color2, bg = palette.bg },
		DiffChange = { fg = palette.color10, bg = palette.bg },
		DiffDelete = { fg = palette.color1, bg = palette.bg },
		DiffText = { fg = palette.color4, bg = palette.bg },
		EndOfBuffer = { fg = palette.bg },
		NonText = { fg = palette.color0 },
		SpecialKey = { fg = palette.color8 },
		Search = { fg = palette.search_fg, bg = palette.search_bg },
		IncSearch = { fg = palette.search_fg, bg = palette.search_bg },
		Substitute = { fg = palette.search_fg, bg = palette.search_bg },
		MatchParen = { fg = palette.color14, bg = palette.color0, bold = true },
		ModeMsg = { fg = palette.fg },
		MsgArea = { fg = palette.fg },
		MoreMsg = { fg = palette.color4 },
		Pmenu = { fg = palette.fg, bg = palette.color0 },
		PmenuSel = { fg = palette.bg, bg = palette.color2 },
		PmenuSbar = { bg = palette.color0 },
		PmenuThumb = { bg = palette.color8 },
		Question = { fg = palette.color4 },
		QuickFixLine = { bg = palette.selection_bg },
		SpellBad = { sp = palette.color1, undercurl = true },
		SpellCap = { sp = palette.color10, undercurl = true },
		SpellLocal = { sp = palette.color5, undercurl = true },
		SpellRare = { sp = palette.color6, undercurl = true },
		TabLine = { fg = palette.inactive_tab_fg, bg = palette.inactive_tab_bg },
		TabLineFill = { bg = palette.bg },
		TabLineSel = { fg = palette.active_tab_fg, bg = palette.active_tab_bg },
		Title = { fg = palette.color4, bold = true },

		-- Treesitter groups
		["@comment"] = { link = "Comment" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { fg = palette.color4, bold = true },
		["@string"] = { link = "String" },
		["@character"] = { link = "Character" },
		["@number"] = { link = "Number" },
		["@boolean"] = { link = "Boolean" },
		["@float"] = { link = "Float" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { fg = palette.color12, bold = true },
		["@parameter"] = { fg = palette.color5 },
		["@method"] = { link = "Function" },
		["@field"] = { fg = palette.color5 },
		["@property"] = { fg = palette.color5 },
		["@constructor"] = { fg = palette.color7 },
		["@conditional"] = { link = "Conditional" },
		["@repeat"] = { link = "Repeat" },
		["@label"] = { link = "Label" },
		["@keyword"] = { link = "Keyword" },
		["@operator"] = { link = "Operator" },
		["@exception"] = { link = "Exception" },
		["@variable"] = { fg = palette.fg },
		["@variable.builtin"] = { fg = palette.color4, bold = true },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = palette.color7, italic = true },
		["@namespace"] = { fg = palette.color7 },
		["@include"] = { link = "Include" },
		["@punctuation.delimiter"] = { fg = palette.fg },
		["@punctuation.bracket"] = { fg = palette.fg },
		["@punctuation.special"] = { fg = palette.color13 },
		["@text"] = { fg = palette.fg },
		["@text.emphasis"] = { italic = true },
		["@text.underline"] = { underline = true },
		["@text.title"] = { bold = true },
		["@text.literal"] = { fg = palette.color6 },
		["@text.uri"] = { fg = palette.color6, underline = true },
		["@tag"] = { fg = palette.color2 },
		["@tag.attribute"] = { fg = palette.color5 },
		["@tag.delimiter"] = { fg = palette.fg },

		-- LSP/Diagnostics
		DiagnosticError = { fg = palette.color14 },
		DiagnosticWarn = { fg = palette.color10 },
		DiagnosticInfo = { fg = palette.color6 },
		DiagnosticHint = { fg = palette.color8 },
		DiagnosticVirtualTextError = { fg = palette.color14, bg = palette.color0 },
		DiagnosticVirtualTextWarn = { fg = palette.color10, bg = palette.color0 },
		DiagnosticVirtualTextInfo = { fg = palette.color6, bg = palette.color0 },
		DiagnosticVirtualTextHint = { fg = palette.color8, bg = palette.color0 },
		DiagnosticUnderlineError = { sp = palette.color14, undercurl = true },
		DiagnosticUnderlineWarn = { sp = palette.color10, undercurl = true },
		DiagnosticUnderlineInfo = { sp = palette.color6, undercurl = true },
		DiagnosticUnderlineHint = { sp = palette.color8, undercurl = true },
		LspSignatureActiveParameter = { bold = true },
		LspCodeLens = { fg = palette.color8 },

		-- Plugin-specific (for LazyVim)
		TelescopeNormal = { fg = palette.fg, bg = palette.bg },
		TelescopeBorder = { fg = palette.color8 },
		TelescopeSelection = { fg = palette.fg, bg = palette.selection_bg },
		NvimTreeNormal = { fg = palette.fg, bg = palette.bg },
		NvimTreeFolderIcon = { fg = palette.color4 },
		NvimTreeIndentMarker = { fg = palette.color8 },
		CmpItemAbbr = { fg = palette.fg },
		CmpItemAbbrMatch = { fg = palette.color4, bold = true },
		CmpItemKind = { fg = palette.color4 },
		LazyNormal = { fg = palette.fg, bg = palette.bg },
		WhichKey = { fg = palette.color4 },
		MasonNormal = { fg = palette.fg, bg = palette.bg },
		-- Add more plugin groups as needed (e.g., for Notify, Bufferline)
	}
end

return { get_groups = get_groups }
